pos-order-detail/pos-order-detail.page.html, pos-payment-modal/pos-payment-modal.page.ts
=> Update Receive Amount + Debt

pos-order-detail/pos-order-detail.page.ts
=> Fix Saving order

pos-for-customer/order/pos-customer-order.page.ts, pos-for-customer/payment/pos-payment-modal.page.html, pos-for-customer/payment/pos-payment-modal.page.scss, pos-for-customer/payment/pos-payment-modal.page.ts, pos-for-customer/welcome/pos-welcome.page.ts, pos-order-detail/pos-order-detail.page.html, pos-order-detail/pos-order-detail.page.ts, pos-payment-modal/pos-payment-modal.page.html, pos-payment-modal/pos-payment-modal.page.scss, pos-payment-modal/pos-payment-modal.page.ts, pos-table-detail/pos-table-detail.page.html, pos-table-detail/pos-table-detail.page.scss, pos-table-detail/pos-table-detail.page.ts
=> Refund , config Table

pos-change-table-modal/pos-change-table-modal.page.ts, pos-for-customer/order/pos-customer-order.page.html, pos-for-customer/order/pos-customer-order.page.scss, pos-for-customer/order/pos-customer-order.page.ts, pos-order-detail/pos-order-detail.page.html, pos-order-detail/pos-order-detail.page.ts, pos-order/pos-order.page.html, pos-order/pos-order.page.ts
IP check, tables valid, autosave, svc design.
1. Kiểm tra IP cho giao diện của khách hàng. Nếu không khớp, hiển thị modal báo kiểm tra và kết nối vào mạng tòa nhà ( Config có thể điều chỉnh trong cấu hình chung >> POS >> Có sử dụng IP  whitelist, và textbox cho nhập IP.
2. Bổ sung thêm Validatior.Required cho bàn >> Xử lý được phần bị lỗi khi mở modal chuyển bàn.
3. Thêm cấu hình chung cho Autosave, nếu không tự động lưu >> Bấm lưu đơn >> Hiển thị prompt có cần in hay không.
4. SVC. Sửa lại hiển thị 3 chỗ ( cashier, khách, phiếu in ). Đảm bảo là thông tin SVC VAT và tổng tiền cuối cùng chính xác.
=> IP check, tables valid, autosave, svc design.

pos-order-detail/pos-order-detail.page.ts
=> Pos update

pos-change-table-modal/pos-change-table-modal.page.ts, pos-for-customer/order/pos-customer-order.page.ts, pos-for-customer/welcome/pos-welcome.page.html, pos-for-customer/welcome/pos-welcome.page.scss, pos-for-customer/welcome/pos-welcome.page.ts, pos-order-detail/pos-order-detail.page.ts
POS Update 
welcome message
Orderline Status
=> POS Update 

pos-for-customer/welcome/pos-welcome.page.scss
=> update pos-welcome position

pos-for-customer/order/pos-customer-order.page.html, pos-for-customer/order/pos-customer-order.page.ts, pos-order-detail/pos-order-detail.page.html, pos-order-detail/pos-order-detail.page.ts
Update IPConfig, Show Memo on lock Lines
=> Update IPConfig, Show Memo on lock Lines

pos-for-customer/order/pos-customer-order.page.html, pos-for-customer/order/pos-customer-order.page.scss, pos-for-customer/order/pos-customer-order.page.ts, pos-for-customer/payment/pos-payment-modal.page.html, pos-order-detail/pos-order-detail.page.html, pos-order-detail/pos-order-detail.page.ts, pos-order/pos-order.page.ts, pos-payment-modal/pos-payment-modal.page.html
=> TemporaryBill cho Đơn POS

pos-for-customer/order/pos-customer-order.page.html, pos-for-customer/order/pos-customer-order.page.ts, pos-order-detail/pos-order-detail.page.ts
Lỗi reload tăng số lượng + khóa tính tiền
=> Lỗi reload tăng số lượng + khóa tính tiền

pos-order-detail/pos-order-detail.page.html, pos-order-detail/pos-order-detail.page.ts
Code quét mã NV từ danh bạ HRO
=> Code quét mã NV từ danh bạ HRO

pos-for-customer/order/pos-customer-order.page.ts, pos-order-detail/pos-order-detail.page.html, pos-order-detail/pos-order-detail.page.ts
=> Create qr temp bill

pos-order-detail/pos-order-detail.page.html
=> Change to 10px temp bill;

pos-order-detail/pos-order-detail.page.html, pos-order-detail/pos-order-detail.page.scss, pos-order-detail/pos-order-detail.page.ts
Update QR Code not showing on PDF + Fix size QR
=> Update QR Code not showing on PDF + Fix size QR

pos-order/pos-order.page.html, pos-order/pos-order.page.ts
=> Update Code Export Data

pos-order/pos-order.page.ts
Tải dữ liệu điều kiện lọc theo ngày, trạng thái
=> Tải dữ liệu điều kiện lọc theo ngày, trạng thái

pos-for-customer/order/pos-customer-order.page.ts, pos-order-detail/pos-order-detail.page.html, pos-order-detail/pos-order-detail.page.ts, pos-order/pos-order.page.ts, pos-orderlines-cancel-modal/pos-orderlines-cancel-modal.page.ts, pos-split-modal/pos-split-modal.page.ts
Cập nhật hủy món + sửa lỗi tracking
=> Cập nhật hủy món + sửa lỗi tracking

pos-order-detail/pos-order-detail.page.html
=> Pos filter deal

pos-for-customer/order/pos-customer-order.page.html, pos-for-customer/order/pos-customer-order.page.scss, pos-for-customer/order/pos-customer-order.page.ts, pos-order-detail/pos-order-detail.page.html, pos-order-detail/pos-order-detail.page.scss, pos-order-detail/pos-order-detail.page.ts, pos-order/pos-order.page.html, pos-order/pos-order.page.scss, pos-order/pos-order.page.ts
Update POS Events fn + FAB styling.
=> Update POS Events fn + FAB styling.

pos-change-table-modal/pos-change-table-modal.page.ts, pos-for-customer/order/pos-customer-order.page.ts, pos-order-detail/pos-order-detail.page.html, pos-order-detail/pos-order-detail.page.ts, pos-order/pos-order.page.html, pos-order/pos-order.page.ts, pos-payment-modal/pos-payment-modal.page.ts, pos-split-modal/pos-split-modal.page.ts
Update POS events, IDAddress, Refunds, Tín hiệu mạng
=> Update POS events, IDAddress, Refunds, Tín hiệu mạng

pos-for-customer/order/pos-customer-order.page.html, pos-for-customer/order/pos-customer-order.page.ts, pos-order-detail/pos-order-detail.page.ts, pos-order/pos-order.page.ts
check LastModdifiedDate from Customer, Notis.
=> check LastModdifiedDate from Customer, Notis.

pos-for-customer/order/pos-customer-order.page.ts, pos-order-detail/pos-order-detail.page.ts, pos-order/pos-order.page.ts
Thêm tên bàn + số lượng món thông báo chưa gửi bếp
=> Thêm tên bàn + số lượng món thông báo chưa gửi bếp
